---
- name: Quick Network Traffic Test
  hosts: client_devices
  gather_facts: no
  
  tasks:
    - name: Install basic network tools
      raw: |
        if command -v apk >/dev/null 2>&1; then
          apk add --no-cache curl wget netcat-openbsd
        elif command -v apt >/dev/null 2>&1; then
          apt-get update && apt-get install -y curl wget netcat iputils-ping
        fi
      ignore_errors: yes

    - name: Quick connectivity and traffic test
      shell: |
        echo "=== Quick Traffic Test from {{ inventory_hostname }} ==="
        
        # Test web server connectivity
        echo "Testing web servers..."
        curl -s --connect-timeout 5 http://192.168.30.10/ && echo "✓ Web server reachable" || echo "✗ Web server failed"
        curl -s --connect-timeout 5 http://192.168.100.10/ && echo "✓ Public web reachable" || echo "✗ Public web failed"
        
        # Test ping connectivity  
        echo "Testing ping connectivity..."
        ping -c 2 192.168.30.11 && echo "✓ DB server ping OK" || echo "✗ DB server ping failed"
        ping -c 2 192.168.30.12 && echo "✓ File server ping OK" || echo "✗ File server ping failed"
        
        # Generate some TCP traffic
        echo "Generating TCP traffic..."
        echo "Hello from {{ inventory_hostname }}" | nc -w 2 192.168.30.10 80 || echo "TCP traffic sent"
        
        echo "=== Traffic test completed ==="
      ignore_errors: yes
